//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorApp.TestClientProject.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorApp.TestClientProject.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        internal static string AuthenticationAccessDenied {
            get {
                return ResourceManager.GetString("AuthenticationAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Error.
        /// </summary>
        internal static string AuthenticationError {
            get {
                return ResourceManager.GetString("AuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        internal static string AuthenticationUnauthorized {
            get {
                return ResourceManager.GetString("AuthenticationUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer first name must be between 1 and 32 characters..
        /// </summary>
        internal static string CustomerFirstNameLength {
            get {
                return ResourceManager.GetString("CustomerFirstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer first name is required..
        /// </summary>
        internal static string CustomerFirstNameRequired {
            get {
                return ResourceManager.GetString("CustomerFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer last name must be between 1 and 32 characters..
        /// </summary>
        internal static string CustomerLastNameLength {
            get {
                return ResourceManager.GetString("CustomerLastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer phone must be between 7 and 32 characters..
        /// </summary>
        internal static string CustomerPhoneLength {
            get {
                return ResourceManager.GetString("CustomerPhoneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A customer phone is required..
        /// </summary>
        internal static string CustomerPhoneRequired {
            get {
                return ResourceManager.GetString("CustomerPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulfillment type must be: CustomerPickup, ShopDelivery, InShop, or IntegrationDelivery..
        /// </summary>
        internal static string InvalidFulfillmentType {
            get {
                return ResourceManager.GetString("InvalidFulfillmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status must be: Accepted, Rejected, Complete, Cancelled, or Changed..
        /// </summary>
        internal static string InvalidStatus {
            get {
                return ResourceManager.GetString("InvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A shop id is required..
        /// </summary>
        internal static string ShopIdRequired {
            get {
                return ResourceManager.GetString("ShopIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order total must be equal or greater than $0..
        /// </summary>
        internal static string TotalGreaterThanZero {
            get {
                return ResourceManager.GetString("TotalGreaterThanZero", resourceCulture);
            }
        }
    }
}
